<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="houzf-PC" ignored="1" name="Default test" tests="1" failures="1" timestamp="31 五月 2018 15:17:47 GMT" time="2.061" errors="0">
  <testcase name="test1" time="2.024" classname="com.test.Timeout">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.test.Timeout.test1() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.Timeout.test1() didn't finish within the time-out 2000
]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test" time="0.0" classname="com.test.Timeout">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- Default test -->
